theme: jekyll-theme-minimal
title: Blake Feiza's Homepage
description: This site serves as a hub for all of my research, certifications, and projects I've completed. Continuously updating with new accolades and achievements.
